---
- name: DIRECTORIES | User home directory
  ansible.builtin.set_fact:
    home_dir: "{{ ansible_env.HOME }}"
  tags:
    - always

- name: DIRECTORIES | Binaries
  block:
    - name: DIRECTORIES | Set binaries directory
      ansible.builtin.set_fact:
        bin_dir: "{{ workstation_bin_dir if workstation_bin_dir.startswith('/') else home_dir + '/' + workstation_bin_dir }}"

    - name: DIRECTORIES | Create binaries directory
      ansible.builtin.file:
        path: "{{ bin_dir }}"
        state: directory
        mode: 0755
      tags:
        - always

- name: DIRECTORIES | Cache
  block:
    - name: DIRECTORIES | Set cache directory
      ansible.builtin.set_fact:
        workstation_cache_dir: "{{ workstation_cache_dir if workstation_cache_dir.startswith('/') else home_dir + '/' + workstation_cache_dir }}"

    - name: DIRECTORIES | Create cache directory
      ansible.builtin.file:
        path: "{{ workstation_cache_dir }}"
        state: directory
        mode: 0755
      tags:
        - always

- name: DIRECTORIES | Fonts
  block:
    - name: DIRECTORIES | Set fonts directory
      ansible.builtin.set_fact:
        workstation_fonts_dir: "{{ workstation_fonts_dir if workstation_fonts_dir.startswith('/') else home_dir + '/' + workstation_fonts_dir }}"

    - name: DIRECTORIES | Create fonts directory
      ansible.builtin.file:
        path: "{{ workstation_fonts_dir }}"
        state: directory
        mode: 0755
      tags:
        - always

- name: Install Snapd
  ansible.builtin.import_tasks: snapd.yml
  tags:
    - workstation
    - snapd

- name: Configure Bash
  ansible.builtin.import_tasks: bash.yml
  tags:
    - workstation
    - bash

- name: Install Chezmoi
  ansible.builtin.import_tasks: chezmoi.yml
  when: workstation_chezmoi_enabled
  tags:
    - workstation
    - chezmoi

- name: Install Kubectl
  ansible.builtin.import_tasks: kubectl.yml
  when: workstation_kubectl_enabled
  tags:
    - workstation
    - kubectl

- name: Install Go
  ansible.builtin.import_tasks: go.yml
  when: workstation_go_enabled
  tags:
    - workstation
    - go

- name: Install Mononoki Fonts
  ansible.builtin.import_tasks: mononoki.yml
  when: workstation_mononoki_enabled
  tags:
    - workstation
    - mononoki
    - fonts

- name: Install Powerline-Go
  ansible.builtin.import_tasks: powerline-go.yml
  when: workstation_powerlinego_enabled
  tags:
    - workstation
    - powerlinego

- name: Install VS Code
  ansible.builtin.import_tasks: vscode.yml
  when: workstation_vscode_enabled
  tags:
    - workstation
    - vscode

- name: Install Pyenv
  ansible.builtin.import_tasks: pyenv.yml
  when: workstation_pyenv_enabled
  tags:
    - workstation
    - pyenv
