---
- name: POWERLINE-GO | Install
  ansible.builtin.command: go install github.com/justjanne/powerline-go@latest

- name: POWERLINE-GO | Create config directory
  ansible.builtin.file:
    path: "{{ home_dir }}/.config/powerline-go"
    state: directory
    mode: 0755

- name: POWERLINE-GO | Copy my theme
  ansible.builtin.copy:
    src: home/.config/powerline-go/personal-theme.json
    dest: "{{ home_dir }}/.config/powerline-go/personal-theme.json"
    mode: 0644

- name: POWERLINE-GO | Add config to bashrc
  ansible.builtin.copy:
    src: home/.bashrc.d/powerline-go.sh
    dest: "{{ home_dir }}/.bashrc.d/powerline-go.sh"
    mode: 0644
